### ISSUE TITLE
NB viewer not loading

### ISSUE THREAD

**Issue by rowanc1** [aranzgeo/steno3d-notebooks#22]
The renderers for the notebooks on github and nbviewer do not render, citing that the JSON might be wrong?

https://nbviewer.jupyter.org/github/aranzgeo/steno3d-notebooks/blob/master/tutorial_point.ipynb

**Comment by fwkoch** [comment]
Thanks for catching this. It was in fact just a problem with trailing commas in the JSON... should be fixed now.
